In [1]:
import pandas as pd
import numpy as np

In [2]:
df_ds = pd.read_csv('titanic.csv')
df=df_ds

In [3]:
df = df.drop(df.columns[[10]],axis = 1)

In [4]:
df = df.dropna(axis=0)

In [99]:
y = input("Enter the Selected Feature Name: ")
df[[y]]

Enter the Selected Feature Name: Age


Age
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
6    54.0
7     2.0
8    27.0
9    14.0
10    4.0
11   58.0
12   20.0
13   39.0
14   14.0
15   55.0
16    2.0
18   31.0
20   35.0
21   34.0
22   15.0
23   28.0
24    8.0
25   38.0
27   19.0
30   40.0
33   66.0
34   28.0
35   42.0
37   21.0
38   18.0
..    ...
856  45.0
857  51.0
858  24.0
860  41.0
861  21.0
862  48.0
864  24.0
865  42.0
866  27.0
867  31.0
869   4.0
870  26.0
871  47.0
872  33.0
873  47.0
874  28.0
875  15.0
876  20.0
877  19.0
879  56.0
880  25.0
881  33.0
882  22.0
883  28.0
884  25.0
885  39.0
886  27.0
887  19.0
889  26.0
890  32.0

[712 rows x 1 columns]

In [47]:
y_1=df.iloc[:,5].values

In [100]:
_type = input("Enter the Feature Type: ")

Enter the Feature Type: Binary


In [22]:
_type

'Binary'

In [25]:
if _type=='Nominal':
    print('Nominal')
elif _type=='Binary':
    print('Binary')
else:
    print('Numeric')

Numeric


In [ ]:
#Replace the with 0 and 1
print(dataset[['Age','Country']])
dataset.describe()
print(dataset['Age']>40)
myFilter=dataset['Age']>=40
myFilter2=dataset['Age']<40
temp_0[myFilter]=1
temp_0[myFilter2]=0

In [31]:
myFilter_1=y_1<18
myFilter_2=y_1>18

In [52]:
y_1[myFilter_1]=0
y_1[myFilter_2]=1

In [73]:
y_1.dtypes

AttributeError: 'numpy.ndarray' object has no attribute 'dtypes'

In [74]:
type(y_1)

numpy.ndarray

In [53]:
y_1

array([ 1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,
        0.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,
        1.,  1.,  1., 18.,  0.,  1.,  1.,  0.,  1., 18.,  0.,  1.,  1.,
        1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,
        0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,
        1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1., 18.,  1.,  1.,
        0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1., 18.,  1.,  1.,
        1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,
        1.,  1.,  1.,  1.,  1., 18.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1

In [57]:
y_2=df[[y]]

In [58]:
y_2

Age
0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
6     1.0
7     0.0
8     1.0
9     0.0
10    0.0
11    1.0
12    1.0
13    1.0
14    0.0
15    1.0
16    0.0
18    1.0
20    1.0
21    1.0
22    0.0
23    1.0
24    0.0
25    1.0
27    1.0
30    1.0
33    1.0
34    1.0
35    1.0
37    1.0
38   18.0
..    ...
856   1.0
857   1.0
858   1.0
860   1.0
861   1.0
862   1.0
864   1.0
865   1.0
866   1.0
867   1.0
869   0.0
870   1.0
871   1.0
872   1.0
873   1.0
874   1.0
875   0.0
876   1.0
877   1.0
879   1.0
880   1.0
881   1.0
882   1.0
883   1.0
884   1.0
885   1.0
886   1.0
887   1.0
889   1.0
890   1.0

[712 rows x 1 columns]

In [67]:
y_2.loc[myFilter_2,'Age']=1

C:\Users\RazaulMunir\Anaconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\RazaulMunir\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [63]:
type(y)

str

In [117]:
#After 16 & 24..Get Column Index
loc=df.columns.get_loc(y)

In [118]:
y_3=df.iloc[:,loc].values

In [121]:
myFilter_1=y_3<=18
myFilter_2=y_3>18

In [125]:
y_3[myFilter_1]=0

In [129]:
y_3[myFilter_2]=1

In [130]:
y_3

array([1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0.,
       1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
       0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1.

In [135]:
X = df.iloc[:,[2,9]].values

In [136]:
from sklearn import preprocessing
lab_enc = preprocessing.LabelEncoder()
y_3 = lab_enc.fit_transform(y_3)

In [139]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y_3, test_size=0.20)

In [140]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(3, weights='distance')

In [141]:
trained_model = clf.fit(X_train, y_train)

In [143]:
y_pred = trained_model.predict(X_test)

In [144]:
y_test

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int64)

In [145]:
y_pred

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0], dtype=int64)

In [146]:
 from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [147]:
confusion_matrix(y_test, y_pred)

array([[ 11,  11],
       [ 18, 103]], dtype=int64)

In [148]:
accuracy_score(y_test, y_pred)

0.7972027972027972

In [149]:
df..unique().tolist()

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 11 columns):
PassengerId    712 non-null int64
Survived       712 non-null int64
Pclass         712 non-null int64
Name           712 non-null object
Sex            712 non-null object
Age            712 non-null float64
SibSp          712 non-null int64
Parch          712 non-null int64
Ticket         712 non-null object
Fare           712 non-null float64
Embarked       712 non-null object
dtypes: float64(2), int64(5), object(4)
memory usage: 66.8+ KB


In [153]:
len(df['Age'].unique().tolist())

2

In [154]:
#Start
df_1=df_ds

In [169]:
X = df_1.iloc[:,[2,9]].values

In [170]:
y_pred = trained_model.predict(X)

In [171]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [173]:
type(y_pred)

numpy.ndarray

In [177]:
df_1['newAge'] = y_pred

In [178]:
df_1

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

# Random Forest:

In [1]:
import pandas as pd
import numpy as np

df_ds = pd.read_csv('titanic.csv')
df=df_ds

df = df.drop(df.columns[[10]],axis = 1)
df = df.dropna(axis=0)

In [2]:
X = df.iloc[:, [2,9]].values  
y = df.iloc[:, 5].values  

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)  

In [4]:
X_train

array([[  1.    ,  50.4958],
       [  1.    , 153.4625],
       [  2.    ,  26.    ],
       ...,
       [  2.    ,  26.    ],
       [  2.    ,  26.    ],
       [  3.    ,  19.2583]])

In [13]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test) 

In [14]:
from sklearn.ensemble import RandomForestRegressor,RandomForestClassifier

regressor = RandomForestRegressor(n_estimators=20, random_state=0)  
regressor.fit(X_train, y_train)  
y_pred = regressor.predict(X_test) 

In [7]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred))) 

Mean Absolute Error: 11.027077274431475
Mean Squared Error: 207.38184144638873
Root Mean Squared Error: 14.400758363585883


In [15]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred))) 

Mean Absolute Error: 11.027077274431475
Mean Squared Error: 207.38184144638873
Root Mean Squared Error: 14.400758363585883


In [16]:
y_pred

array([33.56      , 31.9872624 , 29.835     , 31.9872624 , 27.40543651,
       27.45922619, 20.2575    , 49.3       , 47.61151654, 33.56      ,
       39.46666667, 23.205671  , 33.205     , 28.53175232, 21.21626984,
       33.374225  , 33.37502366,  9.94693452, 40.075     , 31.9872624 ,
       28.08208333, 31.9872624 , 26.63866667, 17.45119048, 37.4       ,
       40.075     , 31.9872624 , 33.56      , 31.40416667, 28.47083333,
       22.2575    , 13.38571429, 21.45      , 27.40543651, 30.5       ,
       31.9872624 , 33.6       , 35.42888889, 47.61151654, 10.76333333,
       33.37502366, 25.92916667, 30.28817861, 25.05147753, 22.65011905,
       35.55      , 48.25166667, 23.77761905, 28.53175232, 28.90666667,
       37.34630952, 21.44995192, 20.58      , 33.37502366, 33.37502366,
       30.28817861, 30.00613237, 27.62084281, 27.70416667, 38.56761905,
       34.53333333, 22.09293651, 33.56666667, 20.07297619, 32.68348973,
       33.6       , 44.285     , 38.56761905, 29.835     , 10.76

In [17]:
y_test

array([28.  , 30.  ,  0.92, 36.  , 47.  , 36.  , 33.  , 65.  , 65.  ,
       14.5 , 30.  , 26.  , 16.  , 19.  , 21.  , 55.  , 29.  ,  0.75,
       52.  , 39.  , 47.  , 40.  , 14.  ,  8.  , 38.  , 55.  , 34.  ,
       26.  , 27.  , 40.  , 64.  , 14.  , 20.  , 22.  ,  4.  , 24.  ,
       38.  , 36.  , 48.  , 54.  , 19.  , 30.  , 39.  , 33.  , 28.  ,
       16.  , 19.  , 24.  , 26.  , 29.  , 24.  , 22.  , 27.  , 30.  ,
       57.  , 25.  , 35.  , 25.  , 48.  , 42.  , 32.  , 51.  , 20.  ,
        3.  , 27.  , 70.  , 40.  , 48.  ,  2.  , 34.  , 30.  , 35.  ,
       18.  , 30.  , 42.  , 40.  ,  2.  , 17.  , 29.  , 23.  , 39.  ,
       56.  , 20.  , 33.  , 58.  , 29.  , 34.  , 28.  , 13.  , 21.  ,
       55.5 , 33.  , 27.  , 17.  , 15.  , 28.  , 33.  , 52.  , 26.  ,
       42.  , 19.  ,  4.  , 34.  , 64.  , 25.  , 19.  , 25.  , 24.  ,
       62.  , 57.  , 21.  , 18.  , 29.  , 31.  , 25.  , 30.  , 34.  ,
       41.  , 34.  , 33.  , 19.  , 18.  , 32.  ,  9.  , 52.  , 48.  ,
        7.  , 31.  ,

In [121]:
#Practice
df_ds = pd.read_csv('titanic.csv')
df=df_ds

In [122]:
x=df.Age

In [123]:
myFilter_3=x.isnull()

In [124]:
x.replace(np.nan,-1, inplace=True)

In [125]:
#y_3=x
y_3=df.iloc[:, 5].values

In [126]:
myFilter_1=y_3<=18
myFilter_2=y_3>18

In [127]:
y_3[myFilter_1]=0

In [128]:
y_3[myFilter_2]=1

In [129]:
y_3[myFilter_3]= -1

In [131]:
df['Real']=y_3

In [132]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex  Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  1.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  1.0      1   
2                               Heikkinen, Miss. Laina  female  1.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  1.0      1   
4                             Allen, Mr. William Henry    male  1.0      0   
5                                     Moran, Mr. James    male -1.0      0   
6                              McCarthy, Mr. Timothy J    male  1.0      0   
7                       Palsson, Master. Gosta Leonard    male  0.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  1.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  0.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female  0.0      1   
11                            Bonnell, Miss. Elizabeth  female  1.0      0   
12                      Saundercock, Mr. William Henry    male  1.0      0   
13                         Andersson, Mr. Anders Johan    male  1.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  0.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  1.0      0   
16                                Rice, Master. Eugene    male  0.0      4   
17                        Williams, Mr. Charles Eugene    male -1.0      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  1.0      1   
19                             Masselmani, Mrs. Fatima  female -1.0      0   
20        

In [90]:
x.replace(np.nan,-1, inplace=True)

In [91]:
x

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
5      -1.0
6      54.0
7       2.0
8      27.0
9      14.0
10      4.0
11     58.0
12     20.0
13     39.0
14     14.0
15     55.0
16      2.0
17     -1.0
18     31.0
19     -1.0
20     35.0
21     34.0
22     15.0
23     28.0
24      8.0
25     38.0
26     -1.0
27     19.0
28     -1.0
29     -1.0
       ... 
861    21.0
862    48.0
863    -1.0
864    24.0
865    42.0
866    27.0
867    31.0
868    -1.0
869     4.0
870    26.0
871    47.0
872    33.0
873    47.0
874    28.0
875    15.0
876    20.0
877    19.0
878    -1.0
879    56.0
880    25.0
881    33.0
882    22.0
883    28.0
884    25.0
885    39.0
886    27.0
887    19.0
888    -1.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [93]:
myFilter_2=y_3>18

C:\Users\RazaulMunir\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.


In [57]:
myFilter_3=y_3.isnull()

AttributeError: 'numpy.ndarray' object has no attribute 'isnull'

In [38]:
y_3[myFilter_1]=0

C:\Users\RazaulMunir\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [54]:
x=df['Age']

In [27]:
x[myFilter_1]=""

C:\Users\RazaulMunir\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [55]:
x.replace(0, np.nan, inplace=True)

In [56]:
x

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
5       NaN
6      54.0
7       2.0
8      27.0
9      14.0
10      4.0
11     58.0
12     20.0
13     39.0
14     14.0
15     55.0
16      2.0
17      NaN
18     31.0
19      NaN
20     35.0
21     34.0
22     15.0
23     28.0
24      8.0
25     38.0
26      NaN
27     19.0
28      NaN
29      NaN
       ... 
861    21.0
862    48.0
863     NaN
864    24.0
865    42.0
866    27.0
867    31.0
868     NaN
869     4.0
870    26.0
871    47.0
872    33.0
873    47.0
874    28.0
875    15.0
876    20.0
877    19.0
878     NaN
879    56.0
880    25.0
881    33.0
882    22.0
883    28.0
884    25.0
885    39.0
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [ ]:
#catch Null
df_n=df_ds
x_n=df_n.Age
myFilter_3n=x_n.isnull()
x_n.replace(np.nan,-1, inplace=True)
y_3_n=df.iloc[:, 5].values
myFilter_1n=y_3_n<=18
myFilter_2n=y_3_n>18
y_3_n[myFilter_1n]=0
y_3_n[myFilter_2n]=1
y_3_n[myFilter_3n]= -1#catch Null
df_n=df_ds_n.copy()
x_n=df_n.Age
myFilter_3n=x_n.isnull()
x_n.replace(np.nan,-1, inplace=True)
y_3_n=df_n.iloc[:, 5].values
myFilter_1n=y_3_n<=18
myFilter_2n=y_3_n>18
y_3_n[myFilter_1n]=0
y_3_n[myFilter_2n]=1
y_3_n[myFilter_3n]= -1
df_ds_n['RealAge'] = y_3_n
df_ds_n['NewAge'] = y_pred

In [ ]:
from sklearn.metrics import accuracy_score

y_test=df_ds_n.iloc[:,12].values

from sklearn import preprocessing
lab_enc = preprocessing.LabelEncoder()
y_3 = lab_enc.fit_transform(y_test)

accuracy_score(y_test, y_pred)