In [1]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [2]:
X = np.array([[0, 2.10, 1.45], 
              [1, 1.18, 1.33], 
              [0, 1.22, 1.27],
              [1, -0.21, -1.19]])

In [3]:
X_with_nan = np.array([[np.nan, 0.87, 1.31], 
                       [np.nan, -0.67, -0.22]])

In [4]:
clf = KNeighborsClassifier(3, weights='distance')
trained_model = clf.fit(X[:,1:], X[:,0])

In [5]:
imputed_values = trained_model.predict(X_with_nan[:,1:])

# Join column of predicted class with their other features
X_with_imputed = np.hstack((imputed_values.reshape(-1,1), X_with_nan[:,1:]))

# Join two feature matrices
np.vstack((X_with_imputed, X))

array([[ 0.  ,  0.87,  1.31],
       [ 1.  , -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

In [7]:
#prctice
ds = np.array([[0, 2.10, 1.45], 
              [1, 1.18, 1.33], 
              [0, 1.22, 1.27],
              [1, -0.21, -1.14],
              [0, -0.11, -1.19],
              [1, -0.17, -1.20],
              [1, -0.21, -1.19]])

In [8]:
ds

array([[ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.14],
       [ 0.  , -0.11, -1.19],
       [ 1.  , -0.17, -1.2 ],
       [ 1.  , -0.21, -1.19]])

In [10]:
X=ds[:,1:]

In [12]:
y=ds[:,0]

In [16]:
y.shape

(7,)

In [15]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [18]:
clf = KNeighborsClassifier(3, weights='distance')
trained_model = clf.fit(X_train, y_train)

In [24]:
y_pred = trained_model.predict(X_test)

In [19]:
X_test

array([[ 1.18,  1.33],
       [-0.21, -1.14]])

In [20]:
y_test

array([1., 1.])

In [25]:
y_pred

array([0., 1.])

In [29]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [26]:
confusion_matrix(y_test, y_pred)

array([[0, 0],
       [1, 1]], dtype=int64)

In [27]:
classification_report(y_test, y_pred)

C:\Users\RazaulMunir\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


'             precision    recall  f1-score   support\n\n        0.0       0.00      0.00      0.00         0\n        1.0       1.00      0.50      0.67         2\n\navg / total       1.00      0.50      0.67         2\n'

In [32]:
accuracy_score(y_test, y_pred)

0.5

In [33]:
#start with one parameter
X=ds[:,2:]

In [36]:
y=ds[:,0]

In [37]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [38]:
clf = KNeighborsClassifier(3, weights='distance')
trained_model = clf.fit(X_train, y_train)

In [39]:
y_pred = trained_model.predict(X_test)

In [40]:
y_pred

array([0., 0.])

In [41]:
y_test

array([1., 1.])

In [42]:
confusion_matrix(y_test, y_pred)

array([[0, 0],
       [2, 0]], dtype=int64)

In [43]:
accuracy_score(y_test, y_pred)

0.0